#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Services/TravelPlan/TravelPlan.API/TravelPlan.API.csproj", "Services/TravelPlan/TravelPlan.API/"]
COPY ["Services/TravelPlan/TravelPlan.Application/TravelPlan.Application.csproj", "Services/TravelPlan/TravelPlan.Application/"]
COPY ["BuildingBlocks/BuildingBlocks.Messaging/BuildingBlocks.Messaging.csproj", "BuildingBlocks/BuildingBlocks.Messaging/"]
COPY ["BuildingBlocks/BuildingBlocks/BuildingBlocks.csproj", "BuildingBlocks/BuildingBlocks/"]
COPY ["Services/TravelPlan/TravelPlan.Domain/TravelPlan.Domain.csproj", "Services/TravelPlan/TravelPlan.Domain/"]
COPY ["Services/TravelPlan/TravelPlan.Infrastructure/TravelPlan.Infrastructure.csproj", "Services/TravelPlan/TravelPlan.Infrastructure/"]
RUN dotnet restore "./Services/TravelPlan/TravelPlan.API/TravelPlan.API.csproj"
COPY . .
WORKDIR "/src/Services/TravelPlan/TravelPlan.API"
RUN dotnet build "./TravelPlan.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TravelPlan.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TravelPlan.API.dll"]