version: '3.4'

services:
  provincedb:
    container_name: provincedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nguyenqb242
      - POSTGRES_DB=ProvinceDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_province:/var/lib/postgresql/data/
      - ./Services/ProvinceVietNam/ProvinceVietNam.API/Database/CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql
      - ./Services/ProvinceVietNam/ProvinceVietNam.API/Scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
  