version: '3.4'

services:
  provincedb:
    container_name: provincedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nguyenqb242
      - POSTGRES_DB=ProvinceDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_province:/var/lib/postgresql/data/
      - ./Services/ProvinceVietNam/ProvinceVietNam.API/Database/CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql
      - ./Services/ProvinceVietNam/ProvinceVietNam.API/Scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
  
  provincevietnam.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8180
      - ASPNETCORE_HTTPS_PORTS=8181
      - ConnectionStrings__Database=Server=provincedb;Port=5432;Database=ProvinceDb;User Id=postgres;Password=nguyenqb242;Include Error Detail=true
    depends_on:
      - provincedb
    ports:
      - "6100:8180"
      - "6160:8181"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
