services:
  identityredis:
    container_name: identityredis
    restart: always
    ports:
     - "6379:6379"

  identitydb:
    container_name: identitydb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nguyenqb242
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - identitydb_data:/var/opt/mssql

  userdb:
    container_name: userdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nguyenqb242
    ports:
      - "1432:1433"
    restart: always
    volumes:
      - userdb_data:/var/opt/mssql

  locationdb:
    container_name: locationdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nguyenqb242
    ports:
      - "1431:1433"
    restart: always
    volumes:
      - locationdb_data:/var/opt/mssql

  travelplandb:
    container_name: travelplandb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nguyenqb242
    ports:
      - "1430:1433"
    restart: always
    volumes:
      - travelplandb_data:/var/opt/mssql

  messagebroker:
    container_name: messagebroker
    hostname: tripjoy-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
 
  notificationredis:
    container_name: notificationredis
    restart: always
    ports:
      - "6378:6379"

  notificationdb:
    container_name: notificationdb
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nguyenqb242
    restart: always
    ports:
      - "1429:1433"
    volumes:
      - notificationdb_data:/var/opt/mssql

  chatdb:
    container_name: chatdb
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nguyenqb242
    restart: always
    ports:
      - "1428:1433"
    volumes:
      - chatdb_data:/var/opt/mssql

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Redis=identityredis:6379
      - ConnectionStrings__DefaultConnection=Server=identitydb,1433;Database=IdentityDb;User Id=sa;Password=Nguyenqb242;TrustServerCertificate=True;
      - PORT=8080
      - ConnectionStrings__SqlConnection=Server=identitydb,1433;Database=IdentityDb;User Id=sa;Password=Nguyenqb242;TrustServerCertificate=True;
    depends_on:
      - identityredis
      - identitydb
    ports:
      - "6200:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  useraccess.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - PORT=8080
      - ConnectionStrings__Database=Server=userdb,1433;Database=UserDb;User Id=sa;Password=Nguyenqb242;Encrypt=False;TrustServerCertificate=True
      - ConnectionStrings__Redis=identityredis:6379
      - AWS__BucketName=movieticketbooking
      - AWS__AccessKey=${AWS_ACCESS_KEY}
      - AWS__SecretKey=${AWS_SECRET_KEY}
      - AWS__Region=${AWS_REGION}
    ports:
      - "6300:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - userdb
      - identityredis

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "7000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - identity.api
      - locationattraction.api
      - useraccess.api
      - travelplan.api

  locationattraction.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=locationdb,1433;Database=LocationDb;User Id=sa;Password=Nguyenqb242;Encrypt=False;TrustServerCertificate=True
    ports:
      - "6400:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - locationdb

  locationattraction.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=locationdb,1433;Database=LocationDb;User Id=sa;Password=Nguyenqb242;Encrypt=False;TrustServerCertificate=True
    ports:
      - "6500:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - locationdb

  travelplan.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=travelplandb,1433;Database=TravelPlanDb;User Id=sa;Password=Nguyenqb242;Encrypt=False;TrustServerCertificate=True
      - AWS__BucketName=movieticketbooking
      - AWS__AccessKey=${AWS_ACCESS_KEY}
      - AWS__SecretKey=${AWS_SECRET_KEY}
      - AWS__Region=${AWS_REGION}
    ports:
      - "6600:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - travelplandb

  notificationuser.signalr:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=notificationdb,1433;Database=NotificationDb;User Id=sa;Password=Nguyenqb242;Encrypt=False;TrustServerCertificate=True
      - ConnectionStrings__Redis=notificationredis:6379
    ports:
      - "6700:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - notificationdb
      - notificationredis
      - messagebroker

  chat.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=chatdb,1433;Database=NotificationDb;User Id=sa;Password=Nguyenqb242;Encrypt=False;TrustServerCertificate=True
    ports:
      - "6800:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - chatdb

networks:
  default:
   driver: bridge
