version: '3.4'

services:
 provincedb:
  image: postgres

 identityredis:
   image: redis

 sqlserveridentity:
  image: mcr.microsoft.com/mssql/server:2017-latest

 provincevietnam.api:
  image: ${DOCKER_REGISTRY-}provincevietnamapi
  build:
   context: .
   dockerfile: Services/ProvinceVietNam/ProvinceVietNam.API/Dockerfile

 identity.api:
   image: ${DOCKER_REGISTRY-}identityapi
   build:
     context: .
     dockerfile: Services/Identity/Identity.API/Dockerfile

<<<<<<< HEAD
 user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile
=======
 # user.api:
 #    image: ${DOCKER_REGISTRY-}userapi
 #    build:
 #      context: .
 #      dockerfile: Services/User/User.API/Dockerfile
>>>>>>> a15b20f6432bac157c3eb8c62d1455aaea90207c

volumes:
  postgres_province:
  mssqlvolume:





