version: '3.4'

services:
  provincedb:
   image: postgres

  identityredis:
    image: redis

  identitydb:
   image: mcr.microsoft.com/mssql/server

  userdb:
   image: mcr.microsoft.com/mssql/server

  provincevietnam.api:
   image: ${DOCKER_REGISTRY-}provincevietnamapi
   build:
    context: .
    dockerfile: Services/ProvinceVietNam/ProvinceVietNam.API/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  useraccess.api:
    image: ${DOCKER_REGISTRY-}useraccessapi
    build:
      context: .
      dockerfile: Services/UserAccess/UserAccess.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_province:
  mssqlvolume:







