version: '3.4'

services:
  provincedb:
    container_name: provincedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nguyenqb242
      - POSTGRES_DB=ProvinceDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_province:/var/lib/postgresql/data/
      - ./Services/ProvinceVietNam/ProvinceVietNam.API/Database/CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql
      - ./Services/ProvinceVietNam/ProvinceVietNam.API/Scripts/init.sh:/docker-entrypoint-initdb.d/init.sh

  identityredis:
    container_name: identityredis
    restart: always
    ports:
     - "6379:6379"

  sqlserveridentity:
    container_name: sqlserveridentity
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Nguyenqb242
        - MSSQL_PID=Express
    hostname: mssql
    ports:
     - "1433:1433"
    restart: always
    volumes:
        -  mssqlvolume:/var/opt/mssql/data
        - ./Services/Identity/Identity.Infrastructure/Database/CreateTables.sql:/usr/src/app/CreateTables.sql
        - ./Services/Identity/Identity.Infrastructure/Scripts/init.sh:/usr/src/app/init.sh
    entrypoint: ["/bin/bash", "/usr/src/app/init.sh"]

  provincevietnam.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8180
      #- ASPNETCORE_HTTPS_PORTS=8181
      - ConnectionStrings__Database=Server=provincedb;Port=5432;Database=ProvinceDb;User Id=postgres;Password=nguyenqb242;Include Error Detail=true
    depends_on:
      - provincedb
    ports:
      - "6100:8180"
      #- "6160:8181"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8280
      #- ASPNETCORE_HTTPS_PORTS=8281
      - ConnectionStrings__Redis=identityredis:6379
      - ConnectionStrings__DefaultConnection=Server=sqlserveridentity,1433;Database=IdentityDb;User Id=sa;Password=Nguyenqb242;TrustServerCertificate=True;
      - ConnectionStrings__SqlConnection=Server=sqlserveridentity,1433;Database=IdentityDb;User Id=sa;Password=Nguyenqb242;TrustServerCertificate=True;
      
    depends_on:
      - identityredis
      - sqlserveridentity
    ports:
      - "6200:8280"
      #- "6260:8281"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: always
    

  authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8380
      #- ASPNETCORE_HTTPS_PORTS=8381
      - SERVER_IP=http://192.168.30.120:6200
    ports:
      - "6300:8380"
      #- "6360:8381"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - identity.api
    restart: always
networks:
  default:
   driver: bridge
