services:
  provincedb:
    container_name: provincedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nguyenqb242
      - POSTGRES_DB=ProvinceDb
    restart: always
    ports:
      - "5432:5433"
    volumes:
      - postgres_province:/var/lib/postgresql/data/
      - ./Services/ProvinceVietNam/ProvinceVietNam.API/Database/CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql
      - ./Services/ProvinceVietNam/ProvinceVietNam.API/Scripts/init.sh:/docker-entrypoint-initdb.d/init.sh

  identityredis:
    container_name: identityredis
    restart: always
    ports:
     - "6379:6379"

  identitydb:
    container_name: identitydb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nguyenqb242
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - identitydb_data:/var/opt/mssql

  userdb:
    container_name: userdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nguyenqb242
    ports:
      - "1432:1433"
    restart: always
    volumes:
      - userdb_data:/var/opt/mssql

  messagebroker:
    container_name: messagebroker
    hostname: tripjoy-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  provincevietnam.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=provincedb;Port=5432;Database=ProvinceDb;User Id=postgres;Password=nguyenqb242;Include Error Detail=true
    depends_on:
      - provincedb
    ports:
      - "6100:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Redis=identityredis:6379
      - ConnectionStrings__DefaultConnection=Server=identitydb,1433;Database=IdentityDb;User Id=sa;Password=Nguyenqb242;TrustServerCertificate=True;
      - PORT=8080
      - ConnectionStrings__SqlConnection=Server=identitydb,1433;Database=IdentityDb;User Id=sa;Password=Nguyenqb242;TrustServerCertificate=True;
    depends_on:
      - identityredis
      - identitydb
    ports:
      - "6200:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  useraccess.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - PORT=8080
      - ConnectionStrings__Database=Server=userdb,1433;Database=UserDb;User Id=sa;Password=Nguyenqb242;Encrypt=False;TrustServerCertificate=True
      - ConnectionStrings__Redis=identityredis:6379
    ports:
      - "6300:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - userdb
      - identityredis

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "7000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - identity.api
networks:
  default:
   driver: bridge




